apiVersion: v1
kind: Service
metadata:
  name: {{ include "zoneminder.fullname" . }}
  labels:
    {{- include "zoneminder.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: 443
      protocol: TCP
      name: http
    - port: {{ .Values.service.notificationPort }}
      targetPort: 9000
      protocol: TCP
      name: notifications
  selector:
    {{- include "zoneminder.selectorLabels" . | nindent 4 }}
